#pragma once

#define GZIP_VERSION_MAJOR 1
#define GZIP_VERSION_MINOR 0
#define GZIP_VERSION_PATCH 0
#define GZIP_VERSION_CODE (GZIP_VERSION_MAJOR * 10000 + GZIP_VERSION_MINOR * 100 + GZIP_VERSION_PATCH)
#define GZIP_VERSION_STRING "1.0.0"
